import React from 'react'

function Home() {
  return (
    <div>
      <h1 className='home'>Home</h1>
      <p className='hometext'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Numquam ad nulla error possimus delectus esse nostrum a iusto animi necessitatibus perspiciatis, ea cumque ab dolorem illo eaque distinctio officiis veritatis iure vero saepe tempore quae voluptatem. Voluptates doloribus unde beatae molestias cupiditate placeat dignissimos qui exercitationem, enim nostrum cumque eveniet sunt id nam reprehenderit at nihil animi aliquam nisi quisquam laboriosam impedit saepe! At placeat nesciunt ullam beatae quasi, quam neque, ipsum et excepturi inventore ipsa cumque, doloribus qui eligendi molestiae atque asperiores laboriosam iusto ab consectetur facilis tempora magnam odio. Accusantium tempore perspiciatis placeat ducimus quos cum eaque et. Odio placeat ipsa sunt autem eveniet blanditiis hic repudiandae animi doloremque, assumenda in praesentium, cupiditate asperiores ipsam excepturi modi quia libero distinctio quaerat sit, ratione ab. Quaerat cupiditate, ratione rerum quo saepe dolore veritatis dolor minima nostrum. Rem id in veritatis magnam est eveniet consequuntur non vero expedita omnis voluptatem sapiente placeat, dolores et natus cumque iste labore neque laboriosam quaerat nisi! Enim molestias dolore itaque, laudantium, voluptatum eum minima ut, nam odit quaerat eius tempora sit repellat inventore beatae recusandae? Aliquid, voluptatum? Pariatur aliquid, repellendus illum necessitatibus asperiores aut distinctio repudiandae maxime quasi veniam repellat? Pariatur enim quo perferendis facere, ex quia, quam quidem hic nemo, consectetur autem? Eveniet, unde expedita? Cupiditate sapiente ut, voluptas laboriosam, consectetur esse tempore quasi maiores enim assumenda minima necessitatibus sed molestias? Fuga, harum. A sapiente consequuntur doloremque veritatis, molestias necessitatibus vel placeat dolore? Sapiente libero incidunt, consequuntur, nisi tenetur nam voluptatem voluptas temporibus mollitia a nemo pariatur quidem facere id ipsam error aperiam minima minus tempora magni vel fuga quo. Quo culpa accusantium non pariatur! Laudantium, voluptate! Dolor, vel itaque. Veritatis laboriosam reiciendis, deserunt inventore itaque nulla eveniet vel, aliquid laudantium cumque quisquam earum nisi eum architecto ipsam. Cumque tempora quam perferendis adipisci.</p>
    </div>
      
  )
}

export default Home